# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name simulate_Z_lambda_horseshoe_cpp
#' @title Simulate Random Effects and Coefficients using Rcpp and Armadillo
#' @description This function simulates random effects and coefficients following the conditional complete posterior distribution using Rcpp and Armadillo for performance improvements.
#' @param y A numeric vector representing the response variable.
#' @param Z A list of lists of matrices representing random effects.
#' @param mu A double representing the mean value.
#' @param lambda A list of vectors representing coefficients.
#' @param W2 A list of vectors representing the local control of random effects.
#' @param sigma2 A double representing the residual variance.
#' @param tau2 A double representing the global control of random effects.
#' @param V_list A list of lists of left singular matrices used for variance calculations.
#' @param D_list A list of lists of matrices for the prior distribution.
#' @param residuals A numeric vector representing the residuals.
#' @return An integer value.
simulate_Z_lambda_horseshoe_cpp <- function(y, Z, mu, lambda, W2, sigma2, tau2, V_list, D_list, residuals) {
    .Call(`_bayrhm_simulate_Z_lambda_horseshoe_cpp`, y, Z, mu, lambda, W2, sigma2, tau2, V_list, D_list, residuals)
}

#' @name simulate_Z_lambda_fusion_cpp
#' @title Simulate Random Effects and Coefficients using Rcpp and Armadillo
#' @description This function simulates random effects and coefficients following the conditional complete posterior distribution using Rcpp and Armadillo for performance improvements.
#' @param y A numeric vector representing the response variable.
#' @param Z A list of lists of matrices representing random effects.
#' @param mu A double representing the mean value.
#' @param lambda A list of vectors representing coefficients.
#' @param W2 A list of vectors representing the local control of random effects limit-conditions of each group.
#' @param Omega2 A list of vectors representing the local control of random effects differences.
#' @param sigma2 A double representing the residual variance.
#' @param tauO2 A double representing the global control of random effects differences.
#' @param V_list A list of lists of left singular matrices used for variance calculations.
#' @param D_list A list of lists of matrices for the prior distribution.
#' @param residuals A numeric vector representing the residuals.
#' @return An integer value.
simulate_Z_lambda_fusion_cpp <- function(y, Z, mu, lambda, W2, Omega2, sigma2, tauO2, V_list, D_list, residuals) {
    .Call(`_bayrhm_simulate_Z_lambda_fusion_cpp`, y, Z, mu, lambda, W2, Omega2, sigma2, tauO2, V_list, D_list, residuals)
}

#' @name simulate_Z_lambda_fused_cpp
#' @title Simulate Random Effects and Coefficients using Rcpp and Armadillo
#' @description This function simulates random effects and coefficients following the conditional complete posterior distribution using Rcpp and Armadillo for performance improvements.
#' @param y A numeric vector representing the response variable.
#' @param Z A list of lists of matrices representing random effects.
#' @param mu A double representing the mean value.
#' @param lambda A list of vectors representing coefficients.
#' @param W2 A list of vectors representing the local control of random effects.
#' @param Omega2 A list of vectors representing the local control of random effects differences.
#' @param sigma2 A double representing the residual variance.
#' @param tauO2 A double representing the global control of random effects differences.
#' @param V_list A list of lists of left singular matrices used for variance calculations.
#' @param D_list A list of lists of matrices for the prior distribution.
#' @param residuals A numeric vector representing the residuals.
#' @return An integer value.
simulate_Z_lambda_fused_cpp <- function(y, Z, mu, lambda, W2, Omega2, sigma2, tauO2, V_list, D_list, residuals) {
    .Call(`_bayrhm_simulate_Z_lambda_fused_cpp`, y, Z, mu, lambda, W2, Omega2, sigma2, tauO2, V_list, D_list, residuals)
}

